// Package taglines holds splitshot's collection of short, sarcastic,
// security-themed one-liners. They show up in the help header, the version
// output, and on the PDF backup sheets. Pure decoration — but morale matters.
package taglines

import (
	"io"
)

// All returns every tagline. The order is stable so tests can rely on it.
func All() []string {
	return taglines
}

// Pick returns the tagline at i modulo the list length, so any index is safe.
func Pick(i int) string {
	return taglines[((i%len(taglines))+len(taglines))%len(taglines)]
}

// Random returns a tagline chosen using a single byte from r. On any read
// error it falls back to the first tagline — a cosmetic feature should never
// be able to take the program down.
func Random(r io.Reader) string {
	buf := make([]byte, 2)
	if _, err := io.ReadFull(r, buf); err != nil {
		return taglines[0]
	}
	n := int(buf[0])<<8 | int(buf[1])
	return Pick(n)
}

// taglines is the master list. Roughly 200 of them, because if you are going
// to be smug about your threat model you may as well rotate the material.
var taglines = []string{
	"Because trusting one piece of paper was getting too exciting.",
	"Split now, panic less later.",
	"Your secret, shattered on purpose.",
	"Entropy you can hold in your hand.",
	"One share to rule them all? Absolutely not.",
	"Lose a share, keep your dignity.",
	"For people who don't trust the cloud, or themselves.",
	"Shamir would be proud. Probably.",
	"Turning paranoia into a workflow.",
	"A password manager for the apocalypse.",
	"Math: still the only thing you can trust.",
	"No single point of failure, including you.",
	"Cold storage for hot secrets.",
	"Distribute the risk, hoard the smugness.",
	"Because memorizing 33 words is a personality flaw.",
	"Your keys, now in convenient fragments.",
	"Threshold cryptography for the chronically cautious.",
	"Three shares walk into a bar. Two leave with the secret.",
	"Secret sharing: trust issues, productized.",
	"The safest secret is the one nobody fully has.",
	"Generate. Split. Forget. Sleep.",
	"Now with 100% more Reed-Solomon checksums.",
	"GF(256): the field where your secrets go to hide.",
	"Burn one share, the rest still don't care.",
	"For the person who labels their backups' backups.",
	"Plausible deniability, sold separately (it's the passphrase).",
	"Recover from anywhere, panic from nowhere.",
	"Your inheritance plan, minus the lawyers.",
	"Because 'I wrote it on a sticky note' is not a strategy.",
	"Splitting secrets so you don't split hairs.",
	"The dead-man's switch you actually understand.",
	"Trust the math, not the marketing.",
	"Crypto, but the boring, useful kind.",
	"A single share knows nothing. Be like the share.",
	"Hand-write your doom-prep in style.",
	"Shares so secure, even you can't leak just one.",
	"Entropy hoarder's starter kit.",
	"Made for vaults, safes, and that one cookie tin.",
	"Reconstruct your secret, not your trauma.",
	"Less 'trust me bro', more Lagrange interpolation.",
	"The mnemonic words your bank wishes it had.",
	"Offline by design, smug by default.",
	"For when the password reset email isn't coming.",
	"Spread your secrets thin, like good butter.",
	"Two-factor? Try N-of-M factor.",
	"Because the single-backup people never tell the survivors.",
	"Slice your secret. Keep the recipe.",
	"Your seed phrase, but with adult supervision.",
	"Designed for the inevitable, not the convenient.",
	"Resilience you can fold into an envelope.",
	"The opposite of 'all eggs, one basket.'",
	"Keep your enemies guessing and your shares apart.",
	"Built for blackouts, break-ins, and bad luck.",
	"Lose the laptop, keep the kingdom.",
	"Secrets that survive you. Pets, sadly, not included.",
	"PBKDF2: making brute force regret showing up.",
	"You against the universe. The universe is down two shares.",
	"Where 'I forgot' meets 'good thing I split it.'",
	"The analog backup the digital age forgot.",
	"Print it, hide it, outlive it.",
	"Now featuring words you can actually spell.",
	"Quietly judging your one-password lifestyle.",
	"Because fireproof safes have a sense of humor.",
	"Cut the secret, not the corners.",
	"Math nerds call it threshold sharing. You call it sleeping well.",
	"For estates, escrows, and end-of-the-world energy.",
	"Your secret, served in tasting portions.",
	"Redundancy is just paranoia with a backup plan.",
	"Don't put all your entropy in one wallet.",
	"The vault door is math. Good luck picking it.",
	"Splitting the difference between loss and leak.",
	"A backup strategy that survives a flood and a divorce.",
	"Because the heir you trust isn't the heir you'd hand everything.",
	"Single shares: maximum mystery, minimum risk.",
	"More secure than your memory, less needy than a cloud.",
	"For the friends you trust, but not that much.",
	"Where losing one piece is a Tuesday, not a tragedy.",
	"Engineered for worst-case, optimized for shrugging.",
	"Reconstructed secrets, zero reconstructed regrets.",
	"Paper-cut your secret into safety.",
	"Trust distributed, blame untraceable.",
	"The 'in case I get hit by a bus' button.",
	"Doomsday prep that fits in a drawer.",
	"Your passphrase is the plot twist.",
	"Made for safe-deposit boxes and tinfoil hats alike.",
	"It's not hoarding if it's cryptographically justified.",
	"Five shares, two needed, infinite peace of mind.",
	"Because 'trust me' is not an encryption scheme.",
	"Some assembly required. That's the feature.",
	"The only sharing that makes things more private.",
	"Survives fire, flood, and your own forgetfulness.",
	"A secret a day keeps the breach away.",
	"Keys to the kingdom, mailed to three castles.",
	"For the spreadsheet of passwords you swore you'd fix.",
	"Outsource trust to mathematics.",
	"Because the screenshot in your photos is not 'secure.'",
	"Shamir's secret sharing, hold the PhD.",
	"Now you see the secret. Now you need two more people.",
	"The grown-up version of hiding the key under the mat.",
	"Built so betrayal needs a quorum.",
	"Risk, divided and conquered.",
	"Your future self says thank you. Loudly.",
	"Splitting secrets since approximately right now.",
	"One sheet, no answers. As intended.",
	"Reassemble the secret, not the panic.",
	"Cryptography for the catastrophically prepared.",
	"Because the recovery codes are in the email you deleted.",
	"Trust, but verify the digest.",
	"For wills, wallets, and worst-case Wednesdays.",
	"The combo lock for your combo locks.",
	"A secret too important to keep in one place.",
	"Shred-resistant. Catastrophe-tolerant. Smug-compatible.",
	"Distribute the keys, centralize the calm.",
	"Where 'I lost it' stops being the end of the story.",
	"Less single point of failure, more many points of denial.",
	"The backup plan for your backup plan's backup.",
	"Hand it to people who'd never team up against you.",
	"Now your secret needs a conspiracy to leak.",
	"Print, fold, bury. You know, normal hobbies.",
	"Because the sticky note fell behind the desk again.",
	"Designed for the day the password reset link expires forever.",
	"A quorum of trust, a minimum of drama.",
	"Make your secret a group project, finally a good one.",
	"Resilient to fire, theft, and overconfidence.",
	"For when 'remember it' was always a lie.",
	"Your secret, in witness protection.",
	"Two of three. Like a good band reunion.",
	"Built to outlast hard drives and grudges.",
	"Math you can mail to your lawyer.",
	"Secrets so split, even subpoenas need a quorum.",
	"The vault that fits in three envelopes.",
	"Because the seed phrase tattoo was a bad idea.",
	"Reconstruct on a clean machine, like a responsible adult.",
	"For the apocalypse, the audit, and the 'oops.'",
	"Trust nobody completely. Trust the threshold.",
	"Keep one share at mom's. She's never losing anything.",
	"Where redundancy meets restraint.",
	"Your master key, mastered by no one alone.",
	"Half a secret is no secret. That's the magic.",
	"Built for hand-offs that should require a handshake quorum.",
	"Cold, offline, and proud of it.",
	"Make losing a backup a non-event.",
	"The opposite of oversharing.",
	"Your data, your rules, your three locations.",
	"For the legacy you can't email.",
	"Encryption optional. Distrust mandatory.",
	"Because cloud sync is just someone else's outage.",
	"Spread the secret, not the panic.",
	"A secret worth keeping is worth splitting.",
	"Three keys, no kings.",
	"The math says relax. So relax.",
	"Built for break-ins you'll never tell anyone about.",
	"Keep calm and reach quorum.",
	"Your safe-deposit box's new best friend.",
	"For people whose threat model includes themselves.",
	"Recover the secret, not the embarrassment.",
	"Now even your paranoia has redundancy.",
	"Single share, single tear, zero leaks.",
	"The estate plan that won't get probated by hackers.",
	"Where 'where did I put it' is finally survivable.",
	"Split your seed, sleep through the storm.",
	"Trust is a luxury; thresholds are insurance.",
	"For the vault, the cabin, and your cousin you sort of trust.",
	"Because two-factor still lives on one phone.",
	"Make your secret impossible to lose and hard to leak.",
	"The cryptographic equivalent of don't-put-it-in-writing, in writing.",
	"Hand-write history-proof backups.",
	"Mathematically allergic to single points of failure.",
	"Built to be boring in a crisis.",
	"Your keys deserve a buddy system.",
	"Slice it like you mean it.",
	"For when 'it's in my head' becomes a liability.",
	"Distributed trust, concentrated calm.",
	"Because the last guy kept it all on one USB stick.",
	"A secret that needs a committee to escape.",
	"Reconstructed only by consensus, never by accident.",
	"The doomsday folder, finally done right.",
	"Words on paper beat passwords in the breach.",
	"Spread thin, recover whole.",
	"For heirs, hardware wallets, and healthy suspicion.",
	"Lose a sheet, keep the secret. That's the deal.",
	"Engineered against the day everything goes wrong at once.",
	"Quorum required. Drama optional.",
	"Your secret survives the fire drill and the real fire.",
	"Because backups you can't test are just hope.",
	"Cut once, recover forever.",
	"For the kind of secret you whisper to math.",
	"More resilient than your last new year's resolution.",
	"Keep the threshold, lose the fear.",
	"Designed so no single envelope is worth stealing.",
	"The grown-up alternative to 'I'll just remember it.'",
	"Three locations, one secret, zero late-night panics.",
	"Secrets so distributed they need a reunion to escape.",
	"For when the only witness you trust is arithmetic.",
	"Because the breach notification always comes too late.",
	"Split it before someone else does it for you.",
	"Built for the long game, the worst day, and the slow leak.",
	"The math has your back, even when nobody else does.",
	"Reassemble with friends, not adversaries.",
	"Your secret's exit requires a quorum visa.",
	"Hoard entropy, distribute trust.",
	"Sleep like someone who split their seed phrase.",
}
